"""initial schema

Revision ID: fb391440fdef
Revises:
Create Date: 2026-08-30 20:49:41.325448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb391440fdef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsk_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('test_code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exam_file', sa.String(length=500), nullable=False),
    sa.Column('answer_file', sa.String(length=500), nullable=True),
    sa.Column('writing_file', sa.String(length=500), nullable=True),
    sa.Column('full_audio_file', sa.String(length=500), nullable=True),
    sa.Column('audio_play_limit', sa.Integer(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('import_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsk_tests_level'), 'hsk_tests', ['level'], unique=False)
    op.create_index('ix_hsk_tests_level_status', 'hsk_tests', ['level', 'status'], unique=False)
    op.create_index(op.f('ix_hsk_tests_source_fingerprint'), 'hsk_tests', ['source_fingerprint'], unique=False)
    op.create_index(op.f('ix_hsk_tests_status'), 'hsk_tests', ['status'], unique=False)
    op.create_index(op.f('ix_hsk_tests_test_code'), 'hsk_tests', ['test_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('section_scores', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['hsk_tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_status'), 'attempts', ['status'], unique=False)
    op.create_index(op.f('ix_attempts_test_id'), 'attempts', ['test_id'], unique=False)
    op.create_index('ix_attempts_test_status', 'attempts', ['test_id', 'status'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_index('ix_attempts_user_status', 'attempts', ['user_id', 'status'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('test_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['hsk_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_test_code'), 'import_logs', ['test_code'], unique=False)
    op.create_index(op.f('ix_import_logs_test_id'), 'import_logs', ['test_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('audio_file', sa.String(length=500), nullable=True),
    sa.Column('image_file', sa.String(length=500), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['hsk_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'number', name='uq_questions_test_number')
    )
    op.create_index(op.f('ix_questions_section'), 'questions', ['section'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.create_index('ix_questions_test_section', 'questions', ['test_id', 'section'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answers_attempt_question')
    )
    op.create_index(op.f('ix_answers_attempt_id'), 'answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('attempt_audio_plays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_audio_plays_attempt_question')
    )
    op.create_index(op.f('ix_attempt_audio_plays_attempt_id'), 'attempt_audio_plays', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_audio_plays_question_id'), 'attempt_audio_plays', ['question_id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'label', name='uq_options_question_label')
    )
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_attempt_audio_plays_question_id'), table_name='attempt_audio_plays')
    op.drop_index(op.f('ix_attempt_audio_plays_attempt_id'), table_name='attempt_audio_plays')
    op.drop_table('attempt_audio_plays')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_attempt_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_questions_test_section', table_name='questions')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_section'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_import_logs_test_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_test_code'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index('ix_attempts_user_status', table_name='attempts')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index('ix_attempts_test_status', table_name='attempts')
    op.drop_index(op.f('ix_attempts_test_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_status'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hsk_tests_test_code'), table_name='hsk_tests')
    op.drop_index(op.f('ix_hsk_tests_status'), table_name='hsk_tests')
    op.drop_index(op.f('ix_hsk_tests_source_fingerprint'), table_name='hsk_tests')
    op.drop_index('ix_hsk_tests_level_status', table_name='hsk_tests')
    op.drop_index(op.f('ix_hsk_tests_level'), table_name='hsk_tests')
    op.drop_table('hsk_tests')
    # ### end Alembic commands ###
